#! /usr/bin/env python
#
# ProjectEuler.net - problem #002
#
# Summary: Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

import sys
one = 1
two = 2
new = 0

evensum=2

print one
print "%d is even. sum: %d" % (two, evensum)
while new < 4 * 10**6:
    new = one + two
    one = two
    two = new
    if new % 2 == 0:
        evensum = evensum + new
        print "%d is even. sum: %d" % (new, evensum)
    else:
        print new

print "\nThis is it: %d" % evensum

